# Copyright (c) 2023, Oct. Developed by Mouaz M. Al-Shahmeh
# https://malshahmeh.web.app
# APIGuide package
name: api_guide
description: API Guide is package to generate API calls documentations like OpenAPI schema.
version: 1.1.8
repository: https://github.com/Eng-Mouaz-M-AlShahmeh/api_guide
issue_tracker: https://github.com/Eng-Mouaz-M-AlShahmeh/api_guide/issues
topics: [api, documentation, integration-api-guide]
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'
dependencies:
  flutter:
    sdk: flutter
    version: ^0.0.0
  url_launcher: ^6.2.6
  flutter_riverpod: ^2.5.1
  flutter_markdown: ^0.7.1
  markdown: ^7.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
screenshots:
  - description: The flutter api_guide package logo.
    path: screenshots/logo.png
